# Generated by Django 5.1.3 on 2024-11-28 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_gender_wishlistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='image',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='mercado_libre_url',
            field=models.URLField(max_length=500),
        ),
    ]
